### ISSUE TITLE
GT75_8SG

### ISSUE THREAD

**Issue by cyberconan** [YoyPa/isw#21]
Hi! This is results for GT75_8SG:
EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 00 00 00 b0 e0 06 49 0f  >..............I.<
000030 03 09 01 0d 50 0a 05 00 6a 18 40 38 71 02 e0 00  >....P...j.@8q...<
000040 00 00 64 00 c2 17 00 00 c2 17 d6 40 d7 0b 00 00  >..d........@....<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 2f 00 37 4b 50 54 58 5f  >......../.7KPTX_<
000070 64 22 14 22 28 37 3c 41 64 00 0a 09 04 03 03 06  >d"."(7<Ad.......<
000080 36 00 2f 39 43 4d 55 5a 61 1e 14 1e 28 37 41 4f  >6./9CMUZa...(7AO<
000090 64 00 07 06 06 06 07 04 02 00 64 02 00 6e 00 00  >d.........d..n..<
0000a0 31 37 41 36 45 4d 53 31 2e 31 30 31 30 33 31 34  >17A6EMS1.1010314<
0000b0 32 30 31 39 31 32 3a 33 32 3a 30 32 c2 17 00 00  >201912:32:02....<
0000c0 00 01 00 00 00 9e c1 00 00 75 01 0c 01 8d 00 00  >.........u......<
0000d0 00 00 20 00 73 00 00 00 00 00 00 80 00 00 00 00  >.. .s...........<
0000e0 e2 02 00 31 10 00 00 00 00 00 00 00 00 00 00 80  >...1............<
0000f0 00 00 80 00 0c 00 05 00 00 00 32 00 00 03 00 00  >..........2.....<
000100

Profile dump 
Value       set @ address    Fan mode
0xc(12)     0xf4(byte244)    Auto

-----------CPU-----------    -----------GPU-----------
Value       set @ address    Value       set @ address
0x37(55°C)  0x6a(byte106)    0x2f(47°C)  0x82(byte130)
0x4b(75°C)  0x6b(byte107)    0x39(57°C)  0x83(byte131)
0x50(80°C)  0x6c(byte108)    0x43(67°C)  0x84(byte132)
0x54(84°C)  0x6d(byte109)    0x4d(77°C)  0x85(byte133)
0x58(88°C)  0x6e(byte110)    0x55(85°C)  0x86(byte134)
0x5f(95°C)  0x6f(byte111)    0x5a(90°C)  0x87(byte135)

0x14(20%)   0x72(byte114)    0x14(20%)   0x8a(byte138)
0x22(34%)   0x73(byte115)    0x1e(30%)   0x8b(byte139)
0x28(40%)   0x74(byte116)    0x28(40%)   0x8c(byte140)
0x37(55%)   0x75(byte117)    0x37(55%)   0x8d(byte141)
0x3c(60%)   0x76(byte118)    0x41(65%)   0x8e(byte142)
0x41(65%)   0x77(byte119)    0x4f(79%)   0x8f(byte143)
0x64(100%)  0x78(byte120)    0x64(100%)  0x90(byte144)

Thanks!!

**Comment by YoyPa** [comment]
added with commit https://github.com/YoyPa/isw/commit/749780cd838d13c44d122cd3602111990059f4ad
