### ISSUE TITLE
Problem with modprobe

### ISSUE THREAD

**Issue by 0serna** [YoyPa/isw#211]
Hi, I have not managed to run on Fedora 34, what I have done is the following
- run the lines from 21 to 25 of the PKGBUILD
- but when running `modprobe ec_sys write_support=1` I have this error:
**modprobe: FATAL: Module ec_sys not found in directory /lib/modules/5.13.12-200.fc34.x86_64**

Can somebody help me? Thank you!

**Comment by donteatsoclose2me** [comment]
Starting in kernel 5.11 (in Fedora 33), Fedora stopped including the ec_sys module in the normal kernel build.  You will need to install kernel-debug
This should also install kernel-debug-core, which is the package that includes ec_sys.ko

Yep, I'm not happy that Fedora made this change, either.

Once you've installed the debug kernel, you'll need to make sure to boot from it.  Select it from the boot menu at startup, and/or modify your grub to make it the default.
