### ISSUE TITLE
Support for GS63 Stealth 8RE

### ISSUE THREAD

**Issue by 66darkmatter99** [YoyPa/isw#23]
Hi there and thanks for doing this.
heres my dump:

EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 00 00 00 b0 e0 06 49 0b  >..............I.<
000030 03 09 01 0d 50 0a 05 00 44 16 88 2c 3a 02 e0 00  >....P...D..,:...<
000040 00 00 5f 00 58 15 00 00 38 14 43 31 28 0c fa 32  >.._.X...8.C1(..2<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 30 00 37 3d 43 49 4f 55  >........0.7=CIOU<
000070 64 1e 1e 2d 37 41 46 4b 50 00 08 03 03 03 03 03  >d..-7AFKP.......<
000080 37 00 37 3d 43 49 4f 55 64 32 00 32 3c 46 4b 4b  >7.7=CIOUd2.2<FKK<
000090 50 00 08 03 03 03 03 03 02 00 64 02 00 6e 00 00  >P.........d..n..<
0000a0 31 36 4b 35 45 4d 53 31 2e 31 30 34 30 36 32 31  >16K5EMS1.1040621<
0000b0 32 30 31 38 31 31 3a 31 32 3a 30 33 f7 14 00 50  >201811:12:03...P<
0000c0 00 01 25 00 00 9e c0 00 00 b3 00 a2 00 e5 00 00  >..%.............<
0000d0 00 00 00 00 70 00 00 00 00 00 00 80 00 00 00 00  >....p...........<
0000e0 e2 02 00 00 10 00 00 00 00 00 00 00 00 83 00 00  >................<
0000f0 00 00 80 00 0c 00 05 00 00 a1 32 00 00 00 00 00  >..........2.....<
000100

Profile dump 
Value       set @ address    Fan mode
0xc(12)     0xf4(byte244)    Auto

-----------CPU-----------    -----------GPU-----------
Value       set @ address    Value       set @ address
0x37(55°C)  0x6a(byte106)    0x37(55°C)  0x82(byte130)
0x3d(61°C)  0x6b(byte107)    0x3d(61°C)  0x83(byte131)
0x43(67°C)  0x6c(byte108)    0x43(67°C)  0x84(byte132)
0x49(73°C)  0x6d(byte109)    0x49(73°C)  0x85(byte133)
0x4f(79°C)  0x6e(byte110)    0x4f(79°C)  0x86(byte134)
0x55(85°C)  0x6f(byte111)    0x55(85°C)  0x87(byte135)

0x1e(30%)   0x72(byte114)    0x0(0%)     0x8a(byte138)
0x2d(45%)   0x73(byte115)    0x32(50%)   0x8b(byte139)
0x37(55%)   0x74(byte116)    0x3c(60%)   0x8c(byte140)
0x41(65%)   0x75(byte117)    0x46(70%)   0x8d(byte141)
0x46(70%)   0x76(byte118)    0x4b(75%)   0x8e(byte142)
0x4b(75%)   0x77(byte119)    0x4b(75%)   0x8f(byte143)
0x50(80%)   0x78(byte120)    0x50(80%)   0x90(byte144)

**Comment by YoyPa** [comment]
Added as 16K5EMS1 https://github.com/YoyPa/isw/commit/bf38bff73d3b7aaf9d534afc34e0a71192d59f5c https://github.com/YoyPa/isw/commit/8a54601102268e7bfb39c07c445ded9eef479647
