### ISSUE TITLE
problem when running isw -r

### ISSUE THREAD

**Issue by Shadowphoenix** [YoyPa/isw#236]
set up: 
i am running a 'ully updated Arch KDE Plasma, 
installed isw via yay
ran modprobe ec_sys as told in the readme
enabled service with systemctl enable isw@16R1EMS1.service and systemctl start isw@16R1EMS1.service without altering isw.conf

whats the issue:
upon running sudo isw -r i get the following error: 
![image](https://user-images.githubusercontent.com/38107036/152895061-600f5477-31a8-4b46-9409-4a1b873604bc.png)

did i do something wrong? if yes how do i fix this issue?

**Comment by stef204** [comment]
what is the output of:

`# ls -l /sys/kernel/debug/ec/ec0` (as root)

Also, you might try the package `isw-git` which builds the latest `master` with the new options.

What is the output of:

`ps aux | grep isw`

and

`systemctl status isw@16R1EMS1.service`

**Comment by Shadowphoenix** [comment]
i just installed isw-git, after a systemctl disable, enable and reboot now it returns the expected boxes with the values. seems like the isw.1.10-package was bugged for me in some way. thanks for the recommendation - i completely forgot a git-version of this existed^^
