### ISSUE TITLE
GS65_9SE

### ISSUE THREAD

**Issue by he58** [YoyPa/isw#30]
EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 00 00 00 b0 e4 06 5a 0b  >..............Z.<
000030 03 09 00 0d 50 0a 05 00 a0 14 60 3b 71 02 e0 00  >....P.....`;q...<
000040 00 00 5c 00 e9 12 00 00 43 11 89 40 28 0c 00 00  >..\.....C..@(...<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 31 00 37 40 46 4c 52 58  >........1.7@FLRX<
000070 64 32 2d 32 3c 46 4b 50 50 00 08 03 03 03 03 03  >d2-2<FKPP.......<
000080 32 00 37 3d 41 47 4d 56 5e 00 00 32 3c 46 50 5a  >2.7=AGMV^..2<FPZ<
000090 5a 00 08 03 03 03 03 05 02 00 64 02 00 6e 00 00  >Z.........d..n..<
0000a0 31 36 51 34 45 4d 53 31 2e 31 30 38 30 33 31 35  >16Q4EMS1.1080315<
0000b0 32 30 31 39 31 31 3a 32 34 3a 35 38 f8 12 00 00  >201911:24:58....<
0000c0 00 01 31 00 00 9e c1 00 00 5c 00 00 00 a0 14 00  >..1......\......<
0000d0 00 00 00 00 70 80 00 00 05 00 00 00 00 00 00 00  >....p...........<
0000e0 e2 02 00 25 10 00 00 00 00 00 00 00 00 9a 00 e4  >...%............<
0000f0 00 00 80 00 0c 8f 05 00 00 00 32 00 00 00 00 00  >..........2.....<
000100

Profile dump 
Value       set @ address    Fan mode
0xc(12)     0xf4(byte244)    Auto

-----------CPU-----------    -----------GPU-----------
Value       set @ address    Value       set @ address
0x37(55°C)  0x6a(byte106)    0x37(55°C)  0x82(byte130)
0x40(64°C)  0x6b(byte107)    0x3d(61°C)  0x83(byte131)
0x46(70°C)  0x6c(byte108)    0x41(65°C)  0x84(byte132)
0x4c(76°C)  0x6d(byte109)    0x47(71°C)  0x85(byte133)
0x52(82°C)  0x6e(byte110)    0x4d(77°C)  0x86(byte134)
0x58(88°C)  0x6f(byte111)    0x56(86°C)  0x87(byte135)

0x2d(45%)   0x72(byte114)    0x0(0%)     0x8a(byte138)
0x32(50%)   0x73(byte115)    0x32(50%)   0x8b(byte139)
0x3c(60%)   0x74(byte116)    0x3c(60%)   0x8c(byte140)
0x46(70%)   0x75(byte117)    0x46(70%)   0x8d(byte141)
0x4b(75%)   0x76(byte118)    0x50(80%)   0x8e(byte142)
0x50(80%)   0x77(byte119)    0x5a(90%)   0x8f(byte143)
0x50(80%)   0x78(byte120)    0x5a(90%)   0x90(byte144)

**Comment by YoyPa** [comment]
it's already supported in the 16Q4EMS1 section.
