### ISSUE TITLE
Support for GT62VR 6RE

### ISSUE THREAD

**Issue by zinchalk** [YoyPa/isw#31]
I know it's a few years old, just wondering if there was support.
[GT62VR_6RE.txt](https://github.com/YoyPa/isw/files/3554666/GT62VR_6RE.txt)

000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 00 00 00 80 c0 06 49 0b  >..............I.<
000030 03 03 00 05 50 0a 05 00 86 15 40 38 26 02 80 00  >....P.....@8&...<
000040 8c 0a 63 00 93 12 d5 00 48 12 a4 40 e4 0b a0 41  >..c.....H..@...A<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 2a 00 34 40 4b 53 5a 61  >........*.4@KSZa<
000070 64 13 13 1a 22 27 2b 2f 36 63 03 03 03 02 03 03  >d..."'+/6c......<
000080 2b 00 3a 41 48 50 58 5f 61 13 13 27 2b 2f 36 3e  >+.:AHPX_a..'+/6><
000090 64 00 03 03 03 03 03 03 06 05 7d 02 64 7d 00 00  >d.........}.d}..<
0000a0 31 36 4c 32 45 4d 53 31 2e 31 30 37 30 32 32 31  >16L2EMS1.1070221<
0000b0 32 30 31 37 31 35 3a 35 31 3a 32 38 93 12 00 10  >201715:51:28....<
0000c0 00 07 23 00 00 00 00 00 00 35 01 ae 01 ae 00 00  >..#......5......<
0000d0 00 00 40 00 7f 00 00 00 00 00 00 80 01 00 00 00  >..@.............<
0000e0 e2 02 00 00 10 00 00 00 00 00 00 00 00 84 00 00  >................<
0000f0 00 00 80 00 0c 00 05 00 00 00 00 00 00 00 00 00  >................<
000100

EC dump 
[0;32;1m       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F[0m

**Comment by YoyPa** [comment]
added with https://github.com/YoyPa/isw/commit/d95fa93a53ddca669826301f6936848d51772b70
